name: Reusable Workflow

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your steps here

      - name: Build and test
        run: |
          echo "This is called_workflow here..........----  Building and testing..."
          # Add your build and test commands here

      # Add more steps if needed
