name: Calling Workflow 1

on:
  push:
    branches:
      - main

jobs:
  call_workflow_1:
       uses: ./.github/workflows/called_workflow_1.yml
       with: 
          var1: "Hello"
          var2: 20
       secrets:
          SECRET_TOKEN1: ${{ secrets.DOCKERHUB_USERNAME }}
          SECRET_TOKEN2: ${{ secrets.DOCKERHUB_TOKEN }}   

      #  secrets: inherit # if no need to specify the secrets it will take the secrets automatically
  call_workflow_use_matrix:
       strategy:
          matrix:
           vars: ["passed_value_var1", "var2", "var3"]
       uses: ./.github/workflows/called_workflow_1.yml
       with: 
          var1: ${{ matrix.vars }}
          var2: ${{ matrix.vars }}
       secrets:
          SECRET_TOKEN1: ${{ secrets.DOCKERHUB_USERNAME }}
          SECRET_TOKEN2: ${{ secrets.DOCKERHUB_TOKEN }}   



  call_workflow_2:
       uses: ./.github/workflows/called_workflow_2.yml     
       