name: Reusable Workflow 2

on:
  workflow_call:

jobs: 
   

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          echo " This is called workflow 2"
