name: Reusable Workflow

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      var1:
        type: string
        description: "Variable 1"
        required: true

      var2:
        type: number
        description: "Variable 2"
        # default: 10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          echo "var1 => ${{ inputs.var1 }} This is called_workflow here..........----  Building and testing..."
          # Add your build and test commands here

      

  next_build: 
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2

       - name: Build and test
         run: |
           echo "var2 => ${{ inputs.var2 }} Build and Test .... This is next build in called workflow 1"
          
 