name: Reusable Workflow

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          echo "This is called_workflow here..........----  Building and testing..."
          # Add your build and test commands here

      

  next_build: 
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
          
       - name: Build and test
         run: |
           echo "Build and Test .... This is next build in called workflow 1"
          
 