# 
name: Workflow for sports club CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  issues:
    types: [opened, edited, milestoned, reopened, closed, assigned, unassigned, labeled, unlabeled, locked, unlocked, transferred, milestoned, demilestoned]

  workflow_dispatch:

# -----------------------------------
  # i will use bash shell and set the working directory to src
  # whaterver i run in the workflow will be executed in the src directory
  # and the commands will be executed in bash shell

defaults:
  run:
    shell: bash
#     working-directory: ./src
    
# -----------------------------------

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'  

    - name: Build with Maven
      run: mvn compile

    - name: Test with Maven
      run: mvn test -DskipCompile

    - name: Create jar file
      run: mvn package -DskipTests -DskipCompile

    - name: Upload jar file
      uses: actions/upload-artifact@v2
      with:
        name: sports-club-jar
        path: ./target/deccan-sport-club-1.1.jar
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot:latest
  # another stage to put comment for testing purpose

  comment:
    runs-on: ubuntu-latest
    steps:
     - name : Comment on issue
       uses: peter-evans/create-or-update-comment@v4
       with:
         issue-number: 1
         body: |
           This is a multi-line test comment
           - With GitHub **Markdown** :sparkles:
           - Created by [create-or-update-comment][1]
           [1]: https://github.com/peter-evans/create-or-update-comment
         reactions: '+1'
      
    
    
