name: Use reusable workflow
on:
  workflow_dispatch:

jobs:
  
  use-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Use reusable workflow

      # if it is in the same repository
        # uses: ./.github/workflows/reusable-workflow.yml

        uses: pranavjames/Github-Action/.github/workflows/reusable-workflow.yml@main
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot:latest
